### ISSUE TITLE
Unresponsive?

### ISSUE THREAD

**Issue by n00bslayr94** [FoxWorn3365/Shopkeepers#20]
[Sun_Jul_16-21.58.42-UTC_2023.log](https://github.com/FoxWorn3365/Shopkeepers/files/12065203/Sun_Jul_16-21.58.42-UTC_2023.log)
 
Running PocketMine-MP 5.3.1

https://github.com/FoxWorn3365/Shopkeepers/assets/132199379/185b117a-386f-4fe2-bc84-29938edcbd62

I can run /shopkeepers command and see the UI menu. If I click config, nothing happens. 
If I do /shopkeepers create NAME, /shopkeepers summon NAME and right click on it - nothing happens. If I shift and click I can see the trades menu but nothing has been set up. If I shift and click a second time, nothing happens.
If you run a command like "/shopkeepers create" the server just crashes.

**Comment by FoxWorn3365** [comment]
Can you share here the crash report?
Thanks :D

**Comment by FoxWorn3365** [comment]
Small update: today at 9PM UTC+2 I'll back to home to fix all of this bugs.
If you share the crash report I can also fix this bug, otherwise I can't even know where I can search for problems.
For the problem with `/sk create` without the NAME arg is a bug reported like 10 days ago and should be fixed in the next version.

**Comment by n00bslayr94** [comment]
[Sun_Jul_23-01.05.02-UTC_2023.log](https://github.com/FoxWorn3365/Shopkeepers/files/12137495/Sun_Jul_23-01.05.02-UTC_2023.log)
This is the crashdump associated with running /sk create without the NAME arg.

The other issues reported dont result in a crash, it's just unresponsive.

**Comment by FoxWorn3365** [comment]
Should be fixed with the new version of InvMenu
